### ISSUE TITLE
Specify in which file copy .env.tpl in README file

### ISSUE THREAD

**Issue by dymio** [beda-software/aidbox-develop-starter-example#1]
In https://github.com/beda-software/aidbox-develop-starter-example/blob/main/README.md you have the line "Copy the file `.env.tpl` into the same directory and replace ...". Change it to "Copy the file `.env.tpl` into `.env` file in the same directory and replace ...".

**Comment by atuonufure** [comment]
Done. https://github.com/beda-software/aidbox-develop-starter-example/commit/ff88580700e8962ff3add91027d703a8c76eca05
